### ISSUE TITLE
duplicated linebreaks when `\n` coincides with the max width position

### ISSUE THREAD

**Issue by danilosampaio** [jonschlinkert/word-wrap#10]
For example:

`wrap('asdfg\nqwert', {width:5})`

Results:

```
asdfg

qwert
```

Instead of:

```
asdfg
qwert
```

**Comment by jonschlinkert** [comment]
marking as a bug. thanks for reporting.

**Comment by curiousdannii** [comment]
Line breaks get duplicated even when the line breaks aren't at the max width.
`wrap("aaa\nbbb")` becomes `"  aaa\n\n  bbb"`

**Comment by jonschlinkert** [comment]
I just noticed this as well independently, thanks for verifying.
