### ISSUE TITLE
Feature request: Option to disallow orphaned word

### ISSUE THREAD

**Issue by olsonpm** [jonschlinkert/word-wrap#13]
In the case where width is passed, it'd be nice to also have the option to disallow orphaned words

I would like to create a pull request for this feature, but first wanted to make sure you'd be on-board with the option.

* Definition of 'word' could be handled by importing the [lodash.words](https://www.npmjs.com/package/lodash.words) package

**Comment by jonschlinkert** [comment]
I'm definitely open to it if you don't don't mind doing the pr to discuss.  `lodash.words` would be fine too, thanks!

**Comment by olsonpm** [comment]
Will do
