### ISSUE TITLE
FYI: a clone of word-wrap now exists

### ISSUE THREAD

**Issue by sawilde** [jonschlinkert/word-wrap#43]
I see that this clone package of [word-wrap](https://github.com/aashutoshrathi/word-wrap) has since replaced word-wrap in a number of repositories.

It looks like they went straight to trimEnd to fix the ReDOS issue.

**Comment by wellwelwel** [comment]
Hi @sawilde, I suggested this fork for some repositories as a provisional measure until it was properly fixed here (the original project), particularly for **optionator** (a direct dependency for **ESLint** and **escodegen**, for example) as seen in:
- https://github.com/gkz/optionator/issues/44#issuecomment-1610549388

I think that if this problem has been solved (#33 and #41), we can safely return to the original project 🎉

---

And, thanks @doowb 🙋🏻‍♂️

**Comment by sawilde** [comment]
Nice, that was how I came across it when I looked to upgrade word-wrap and noticed the eslint dependency.
