### ISSUE TITLE
Regular Expression Denial of Service

### ISSUE THREAD

**Issue by aalejandromr** [jonschlinkert/word-wrap#44]
Snyk has a security vulnerability report for word-wrap version 1.2.4 https://security.snyk.io/vuln/SNYK-JS-WORDWRAP-3149973

**Comment by bolt-io** [comment]
1.2.3 had the vulnerability. It was fixed in #33 and version 1.2.4

**Comment by doowb** [comment]
Correct, this is fixed in `1.2.4`.

@snyk @lirantal when will this be updated?

**Comment by lirantal** [comment]
Thanks for the ping. I'll share with the security analysts team and get this looked at.

**Comment by lirantal** [comment]
This should be fixed @1.2.4 as of last Thursday, see here: https://security.snyk.io/vuln/SNYK-JS-WORDWRAP-3149973
Let me know if we're still missing anything.

**Comment by doowb** [comment]
Thanks!
