### ISSUE TITLE
More than one whitespace that ends up at the end of a line causes bad indent

### ISSUE THREAD

**Issue by hildjj** [jonschlinkert/word-wrap#6]
This code:

```js
var ww = require('word-wrap');
word-wrap('foo foo.  bar', {width:8})
```

should return `__foo foo.__\n__bar`, but returns `__foo foo._\n___bar`.  (with relevant spaces turned into _).  Note that the incorrect version has *3* spaces before `bar`.  I propose changing your regexp so that the `\s`'s are `\s+`.

**Comment by jonschlinkert** [comment]
hey @hildjj! Do you want to do a pr with a unit test? If not, I can make the changes. thanks for letting me know.

**Comment by hildjj** [comment]
I will add a unit test to my PR
