### ISSUE TITLE
Add options to break words if encounters long words.

### ISSUE THREAD

**Issue by hyaocuk** [jonschlinkert/word-wrap#8]
When we meet a paragraph contains some very long words:
```
this is a veryveryveryveryveryveryverylonglongloooooongword, what should we do to handle this veryveryveryveryverylooooongword?
```
Should it look like this under specific width:
```
this is a veryveryveryveryveryveryvery-
longlongloooooongword, what should 
we do to handle this veryveryveryvery-
verylooooongword?
```

**Comment by jonschlinkert** [comment]
hmm, that's an interesting challenge. I'll try to come up with something

**Comment by danilosampaio** [comment]
hi @jonschlinkert 

a simpler feature would be cuttting the words longer then maxLength, when cut option is true:

```
var re = new RegExp('.{1,' + width + '}(\\s+|$)|\\S+?(\\s+|$)', 'g');

if (opts.cut) {
	re = new RegExp('.{1,' + maxLength + '}', 'g');
}
```

interested in a PR?

**Comment by jonschlinkert** [comment]
makes sense, a PR would be great. thanks!

**Comment by jonschlinkert** [comment]
closed via https://github.com/jonschlinkert/word-wrap/issues/9.

thanks @danilosampaio! https://github.com/jonschlinkert/word-wrap/releases/tag/1.1.0

**Comment by danilosampaio** [comment]
nice! :+1:
